version: "3.8"

services:
  app:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - type: bind
        source: /opt/app_data
        target: /code/app/app_data
    ports:
      - "80:80"
    expose:
      - "80"

